language: java

before_install:
  # install 32bit libraries
  - sudo apt-get update -qq
  - sudo apt-get install -qq libstdc++6:i386 lib32z1

  # download and extract android SDK
  - wget http://dl.google.com/android/android-sdk_r22.3-linux.tgz
  - tar xf android-sdk_r22.3-linux.tgz

  # set PATH and ANDROID_HOME environment
  - export ANDROID_HOME=$PWD/android-sdk-linux
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools

  # update android to specific version
  - echo y | android update sdk --filter platform-tools,extra-android-support,addon-google_apis-google-19,extra-google-google_play_services,android-19,build-tools-19.0.1 --no-ui -a --force

  # fetch google play services into local maven repository
  - git clone git://github.com/mosabua/maven-android-sdk-deployer.git ../deployer
  - cd ../deployer/extras/google-play-services
  - mvn install -N -q
  - cd -
