language: java

before_install:
  # download and extract android SDK
  - wget http://dl.google.com/android/android-sdk_r22.3-linux.tgz
  - tar xf android-sdk_r22.3-linux.tgz

  # set PATH and ANDROID_HOME environment
  - export ANDROID_HOME=$PWD/android-sdk-linux
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools

  # update android to specific version
  - echo y | android update sdk --filter platform-tools,android-18,extra-android-support --no-ui -a --force
